# Final Project - Matrix Factorization & Principal Component Analysis
## CSPB 2820 -  Linear Algebra with Computer Science Applications
*Name*: Patrick Sharp

Submit only this Jupyter notebook with the name format `Final_Project_<yourname>.ipynb`. Do not compress it using tar, rar, zip, etc. You must test this notebook in Jupyter Lab.
Your solutions to analysis questions should be written directly below the associated question. You can add a write-up markdown cell or an extra Python cell if it wasn't provided.

All the written code must be commented as shown in this link https://realpython.com/python-comments-guide/ 

Remember that you are encouraged to discuss the problems with your classmates and instructors, 
but *you must write all code and solutions on your own*, and list any people or sources consulted.

In [3]:
import numpy as np
import tests

## Elementary Review

In [4]:
a = np.arange(15).reshape(3, 5)
print(a)
b = np.arange(15).reshape(5, 3)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Dot product of two arrays can be calculated using the numpy.dot() function from the numpy library

In [5]:
print(np.dot(a,b))

[[ 90 100 110]
 [240 275 310]
 [390 450 510]]


# Problem 1 : What is a Matrix Factorization? [30 points]

A matrix factorization is a way of reducing a matrix into its constituent parts.

It is an approach that can simplify more complex matrix operations that can be performed on the factorized matrix rather than on the original matrix itself.

NOTE: You can choose to implement any one of the two matrix factorization method (LU and Cholesky) and gain 7 marks each. QR Matrix Factorization and Singular-Value Decomposition are complusory.

# 1.1 : LU Matrix Factorization




    The LU Factorization is for square matrices and Factorizes a matrix into L and U components.

**A = L.U or LU**

    Where A is the square matrix that we wish to Factorize, L is the lower triangle matrix and U is the upper triangle matrix.

## LU Factorization with partial pivoting**

    A variation of the LU Factorization that is numerically more stable to solve in practice.

**A = P . L . U**

    The rows of the parent matrix are re-ordered to simplify the Factorization process and the additional P matrix specifies a way to permute the result or return the result to the original order.

Please refer to https://en.wikipedia.org/wiki/LU_decomposition for more details.

In [7]:
from numpy import array
from scipy.linalg import lu

In [8]:
# define a square matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

# LU decomposition
P, L, U = lu(A)
print(P)
print(L)
print(U)

# reconstruct
B = P.dot(L).dot(U)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### Question 1 : Will the LU factorization without Pivoting work on both square and non-square matrices ? Explain with reasons. [2 points]

### Answer :  LU factorization can work for square matrices, but not non-square matrices. The reason it does not work for non-square matrices is that the elimination process may encounter a situation where it needs to divide by zero or perform operations that lead to inconsistencies due to the mismatch in the number of rows and columns. This makes LU factorization without pivoting unsuitable for non-square matrices.



Please refer to https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu.html for more information on the LU library used above.

## Implement the LU factorization methodology from scratch and test it using the same example as above.
  

##   [1.11] Complete the Matrix_multiplication function. [2 Point]
##   [1.12] Complete the Pivot_Calculation function. [2 Point]
##   [1.13] Complete the LU_Factorizer function. [4 Points]



In [54]:
class LU_Factorization:

    def __init__(self, matrix = None):
        """
        Create a LU Factorizer
        :param matrix: Matrix that needs to be factorized

        """

        self.matrix = matrix 

    def Matrix_Multiplication(self, X, Y):
        """
        Create a function to multiply 2 square matrices of same shape
        :param X and Y: 2 matrices of shape (m,n) respectively that are to be multiplied.
        :return: Matrix of shape (m,m)
        """

        # Workspace 1.11
        # TO DO: Complete this function to return the multiplied matrix.
        #BEGIN 
        X_m_rows = len(X)   # number of rows in matrix X
        X_m_cols = len(X[0]) # number of cols in matrix X

        Y_m_rows = len(Y)  # number of rows in matrix Y
        Y_m_cols = len(Y[0]) # number of cols in matrix X
        
        # Check to see if the dimension are fit for matrix multiplication
        if X_m_cols != Y_m_rows: return None
        
        # Check to see if the matrices are square and of the same size
        if X_m_cols != X_m_rows or Y_m_cols != Y_m_rows or X_m_cols != Y_m_cols or X_m_rows != Y_m_rows:
            print('the matrices are not square and the same shape')
            return None

        # initialize the return matrix of size m x m
        return_matrix = np.zeros(X_m_rows*Y_m_cols).reshape(X_m_rows,Y_m_cols)

        # n^3 complexity loop for matrix multiplication
        for i in range(X_m_rows):    # Row of X being multiplied
            for j in range(Y_m_cols): # Col of Y being multiplied
                for k in range(X_m_rows): # element from each for the product to be summed (inner product)
                    return_matrix[i][j] += X[i][k] * Y[k][j] 

        return return_matrix
        # End

    def Pivot_Calculation(self):
        """
        Create a function to calculate the pivoting matrix for the given LU_Factorization object.
        :return: Matrix of shape (m,n)
        """

        # Workspace 1.12
        # TO DO: Complete this function to return the Pivot matrix.
        #BEGIN 
        n = len(self.matrix) # find the number of rows in the matrix
        A = self.matrix.copy()
        
        # build the identity matrix for the pivot matrix
        P = np.eye(n)
                    
                    
        for j in range(n):
            max_index = j
            for i in range(j,n):
                if A[i][j] > A[max_index][j]:
                    max_index = i
            temp = P[j].copy()
            P[j] = P[max_index ]
            P[max_index ] = temp
            temp = A[j].copy()
            A[j] = A[max_index ]
            A[max_index ] = temp
        
        '''
        # Row swap for the pivot
        for j in range(n-1):
            if abs(A[j][j]) < abs(A[j+1][j]):
                temp = P[j].copy()
                P[j] = P[j+1]
                P[j+1] = temp
                temp = A[j].copy()
                A[j] = A[j+1]
                A[j+1] = temp
        '''
                
        return P
        # End

    def LU_Factorizer(self):
        """
        Create a function to factorize matrix for the given LU_Factorization object.
        :return: Return the Matrices P, L and U.
        """

        # Workspace 1.12
        # TO DO: Complete this function to return the P, L and U matrices.
        #BEGIN 
        #P = self.Pivot_Calculation() # Use the pivot_calculation function above to get P
        
        
        n = len(self.matrix)
        U = self.matrix.copy()
        P = np.eye(n)
        L = np.eye(n)
        
        # Row exchange
        for j in range(n):
            max_index = j
            for i in range(j,n):
                if U[i][j] > U[max_index][j]:
                    max_index = i
            temp = P[j].copy()
            P[j] = P[max_index]
            P[max_index ] = temp
            temp = U[j].copy()
            U[j] = U[max_index]
            U[max_index] = temp
        
        
        

        return (P,L,U)
        # End


In [55]:
tests.testLU(LU_Factorization)

Question 1.11: [PASS]
Question 1.12: [FAIL] Testing LU Factorization Pivot Calculation
 Matrix:[[1 2 3]
 [4 5 6]
 [7 8 9]]
 expected output:BBBB [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
 obtained: [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
Question 1.13: [FAIL] Testing LU Factorization LU Factorizer
 Matrix:[[1 2 3]
 [4 5 6]
 [7 8 9]]
 expected output: 
 P[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
 L[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
 U[[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]
 obtained: 
 P[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
 L[[-0.3333333333333333, 1.3333333333333333, inf], [-0.3333333333333333, 1.3333333333333333, inf], [-0.3333333333333333, 1.3333333333333333, inf]]
 U[[-3.0, 2.0, 0.0], [-3.0, 2.0, 0.0], [-3.0, 2.0, 0.0]]


C:\Users\Patri\AppData\Local\Temp\ipykernel_35820\1171103818.py:136: RuntimeWarning: divide by zero encountered in scalar divide
  L[i][j] = (PA[i][j] - s2) / U[j][j]


# 1.2 : QR Matrix Factorization


    The QR Factorization is for m x n matrices (not limited to square matrices) and decomposes a matrix into Q and R components.

**A = Q . R or QR**

    Where A is the matrix that we wish to Factorize, Q a matrix with the size m x m, and R is an upper triangle matrix with the size m x n.

Please refer to https://en.wikipedia.org/wiki/QR_decomposition for more details.

In [ ]:
from numpy import array
from scipy.linalg import qr

In [ ]:
# QR decomposition
# define a 3x2 matrix
A = array([[60, 91, 26], [60, 3, 75], [45, 90, 31]])
D = np.diag(np.sign(np.diag(A)))
print(A)

# QR decomposition
Q_intermediate, R_intermediate = qr(A)
Q_diagonal = np.diag(np.sign(np.diag(Q_intermediate)))
Q = np.matmul(Q_intermediate, Q_diagonal)
R = np.matmul(Q_diagonal,R_intermediate)

print(Q)
print(R)

Please refer to https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.qr.html for more information on the QR library used above.

## Please implement the QR factorization methodology from scratch and test it using the same example as above.
  

##   [1.21] Complete the Norm_Calculation function. [6 Points]
##   [1.22] Complete the Matrix_Multiplication function. [8 Points]
##   [1.23] Complete the QR_Factorizer function. [24 Points]

          Note - Do not implement the code given in the VMLS Python Companion book from Chapter 10 as it is.
          Hint - Make use of the 1.21 and 1.22 functions.


In [ ]:
class QR_Factorization:

    def __init__(self, matrix = None):
        """
        Create a QR Factorizer
        :param matrix: Matrix that needs to be factorized

        """

        self.matrix = matrix 

    def Norm_Calculation(self,A):
        """
        Create a function to calculate the Euclidean norm of a matrix.
        :param A: Matrix for which norm is to be calculated.
        :return: Return a floating point Norm value.
        """

        # Workspace 1.21
        # TO DO: Complete this function to return the Norm of a matrix.
        #BEGIN 
        m = len(A)
        n = len(A[0])
        
        
                
        # End

    def Matrix_Multiplication(self, X, Y):
        """
        Create a function to multiply 2 square matrices of same shape
        :param X and Y: 2 matrices of shape (m,n) respectively that are to be multiplied.
        :return: Matrix of shape (m,m)
        """

        # Workspace 1.22
        # TO DO: Complete this function to return the multiplied matrix.
        #BEGIN 
        
        m = len(X)
        n = len(Y[0])
        
        # Check to see if the dimension are fit for matrix multiplication
        if len(X[0]) != len(Y): return None
        
        return_matrix = np.zeros(m * n).reshape(m,n)
        
        
        
        # End

    def QR_Factorizer(self):
        """
        Create a function to factorize matrix for the given QR_Factorization object using Gram Schmidt Process.
        :return: Return the Matrices Q and R.
        """

        # Workspace 1.23
        # TO DO: Complete this function to return the Q and R matrices.
        #BEGIN 
        # code here
        
        # End


In [ ]:
tests.testQR(QR_Factorization)

### Question 2 : Will the code you have written work on both square and non square matrices ? [2 points]

### Answer :

# 1.3 : Cholesky Matrix Factorization 


    The Cholesky Factorization is for square symmetric matrices where all eigenvalues are greater than zero, so-called positive definite matrices.

**A = L . L^T**

     Where A is the matrix being Factorized, L is the lower triangular matrix and L^T is the transpose of L.

**A = U^T . U**

    Where U is the upper triangular matrix.


Please refer to the https://en.wikipedia.org/wiki/Cholesky_decomposition for more details.

In [ ]:
from numpy import array
from scipy.linalg import cholesky

In [ ]:
# Cholesky factorization
# define a 3x3 matrix
A = array([[2, 1, 1], [1, 2, 1], [1, 1, 2]])
print(A)

L = cholesky(A)
print(L)

### Question 3 : Provide examples for Cholesky Factorization using both Upper Triangular and Lower Triangualar matrices. [2 points]

### Answer :

Please refer to https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.cholesky.html for more information on the Cholesky library used above.

## Please implement the Cholesky factorization methodology from scratch and test it using the same example as above.
  

##  [1.3] Complete the Cholesky_Factorizer. [4 Points]

          Note - Do not implement the code given in the VMLS Python Companion book as it is.
          Hint - Make use of the 1.21 and 1.22 functions.

In [ ]:
class Cholesky_Factorization:

    def __init__(self, matrix = None):
        """
        Create a Cholesky Factorizer
        :param matrix: Matrix that needs to be factorized

        """

        self.matrix = matrix 


    def Cholesky_Factorizer(self):
        """
        Create a function to factorize matrix for the given Cholesky_Factorization object.
        :return: Return the Matrix L or U.
        """

        # Workspace 1.31
        # TO DO: Complete this function to return the Q and R matrices.
        #BEGIN 
        # code here

        # End

In [ ]:
tests.testCholesky(Cholesky_Factorization)

# 1.4 : Singular-Value Decomposition

    The Singular-Value Decomposition, or SVD for short, is a matrix decomposition method for reducing a matrix to its constituent parts in order to make certain subsequent matrix calculations simpler.

    For the case of simplicity we will focus on the SVD for real-valued matrices and ignore the case for complex numbers.

**A = U . Sigma . V^T**

    Where A is the real m x n matrix that we wish to decompose, U is an m x m matrix, Sigma (often represented by the uppercase Greek letter Sigma) is an m x n diagonal matrix, and V^T is the  transpose of an n x n matrix where T is a superscript.

    The diagonal values in the Sigma matrix are known as the singular values of the original matrix A. The columns of the U matrix are called the left-singular vectors of A, and the columns of V are called the right-singular vectors of A.


### Question 4 : Explain how we can find Pseudo inverse of a matrix using SVD. [4 points]

### Answer :

Please refer to the https://en.wikipedia.org/wiki/Singular_value_decomposition for more details.

In [ ]:
from numpy import array
from scipy.linalg import svd

In [ ]:
# Singular-value decomposition
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)

# SVD
U, s, VT = svd(A)
print(U)
print(s)
print(VT)

##   [1.4] Using the above U, s and VT matrices, construct the original A matrix.[10 Points]

In [ ]:
# Workspace 1.41
#BEGIN 
# code here
class SVD:

    def __init__(self, U=None, Sigma=None, VT=None, shape=None):
        """
        Create a Cholesky Factorizer
        """

        self.U = U 
        self.Sigma = Sigma
        self.VT = VT
        self.shape = [3,2]

    def Reconstruct_SVD(self):
        """
        Create a function to reconstruct the original matrix using the 3 matrices generated by SVD.
        :return: Return the Original Matrix.
        """

        # Workspace 1.41
        # TO DO: Complete this function to return the original matrix.
        #BEGIN 
        # code here
     
        # End


#END

In [ ]:
tests.testSVD(SVD)

# Introduction to Eigenvectors and Eigenvalues

An eigenvector of a matrix \(A\) is a vector that when multiplied by \(A\) returns a vector which is ascalar multiple of itself, i.e.,

\(Av\)=\(lambda v\)

Here, \(v\) is called the eigenvector of \(A\), and \(lambda\) is the scalar coefficient, which is called the eigenvalue.

In [ ]:
A=array([[2, 1, 1], [1, 2, 1], [1, 1, 2]])
print(np.linalg.eig(A))

Please refer to https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors , https://medium.com/sho-jp/linear-algebra-part-6-eigenvalues-and-eigenvectors-35365dc4365a for more details

# Covariance of a Matrix 

Covariance provides the a measure of strength of correlation between two variable or more set of variables. The covariance matrix element Cij is the covariance of xi and xj. The element Cii is the variance of xi. 

    If COV(xi, xj) = 0 then variables are uncorrelated
    If COV(xi, xj) > 0 then variables positively correlated
    If COV(xi, xj) < 0 then variables negatively correlated

In [ ]:
import numpy as np

In [ ]:
x = np.array([[0, 3, 4], [1, 2, 4], [3, 4, 5]])
 
print("Shape of array:\n", np.shape(x))
 
print("Covariance matrix of x:\n", np.cov(x))

### Question 5 : Explain the significance of Covariance in a Dataset. [4 points]


### ANSWER :



# Principal Component Analysis

Principal component analysis, or PCA, is a powerful tool which is used to analyze data sets and is formulated in the language of linear algebra and statistics. It is an eigenvalue method used to reduce the dimension of a data set while preserving important information.

Please refer to https://en.wikipedia.org/wiki/Principal_component_analysis for more details.

In [ ]:
from sklearn.decomposition import PCA
import numpy as np 

In [ ]:
np.set_printoptions(precision=3)

B = np.array([[1.0,2], [3,4], [5,6]])

B1 = B.copy() 
B1 -= np.mean(B1, axis=0) 
n_samples = B1.shape[0]
print("B1 is B after centering:")
print(B1)

cov_mat = np.cov(B1.T)
pca = PCA(n_components=2) 
X = pca.fit_transform(B1)
print("X")
print(X)

eigenvecmat =   []
print("Eigenvectors:")
for eigenvector in pca.components_:
    if eigenvecmat == []:
        eigenvecmat = eigenvector
    else:
        eigenvecmat = np.vstack((eigenvecmat, eigenvector))
    print(eigenvector)
print("eigenvector-matrix")
print(eigenvecmat)

print("CHECK FOR PCA:")
print("X * eigenvector-matrix (=B1)")
print(np.dot(X, eigenvecmat))

Please refer to https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html for more details on the PCA library used above.

# Using PCA for Logistic Regression

In [ ]:
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
import sklearn.metrics as metric
import statsmodels.api as sm

In [ ]:
cancer = load_breast_cancer()

data = pd.DataFrame(cancer['data'],columns=cancer['feature_names'])
data['y'] = cancer['target']

In [ ]:
group = [['mean symmetry', 'symmetry error','worst symmetry',
'mean smoothness','smoothness error','worst smoothness']]

In [ ]:
for i,g in enumerate(group):

    x = data[g]
    x = sm.add_constant(x)
    y = data['y']
    x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3, 
                                                        random_state = 101)

    model = sm.Logit(y_train,x_train).fit() #fit logistic regression model

    predictions = np.around(model.predict(x_test))
    accuracy = metric.accuracy_score(y_test,predictions)
    
    print("Accuracy of Group {}: {}".format(i+1,accuracy))

## Use PCA on the above data and fit the data into a Logistic Regression Model. [18 points]

In [ ]:
from sklearn import preprocessing

In [ ]:
#Code Here

### Question 6 : Was there any improvement on the performance of the Logistic Regression model after applying PCA on the data ? If so why ? [4 points]

### Answer : 